// AUTO-GENERATED by gen_map.py — vintage cartographic basemap of the GTA.
// Static server component (no JS). Real lon/lat projected into a 1200x720
// viewBox; the interactive city pins live in MapSection and overlay this.
// Regenerate rather than hand-editing.
export default function MapArt() {
  return (
      <svg viewBox="0 0 1200 720" className="absolute inset-0 h-full w-full" preserveAspectRatio="xMidYMid slice" aria-hidden="true">
      <defs>
      <filter id="grain"><feTurbulence type="fractalNoise" baseFrequency="0.012 0.018" numOctaves="3" seed="7" result="n"/><feColorMatrix in="n" type="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"/><feComposite operator="in" in2="SourceGraphic"/><feComponentTransfer><feFuncA type="linear" slope="0.10"/></feComponentTransfer></filter>
      <filter id="rough"><feTurbulence type="fractalNoise" baseFrequency="0.02" numOctaves="2" seed="3" result="t"/><feDisplacementMap in="SourceGraphic" in2="t" scale="3.2"/></filter>
      <filter id="soft"><feGaussianBlur stdDeviation="6"/></filter>
      <pattern id="stipple" width="9" height="9" patternUnits="userSpaceOnUse" patternTransform="rotate(8)"><circle cx="2" cy="2" r="0.7" fill="#AFC0B8" opacity="0.55"/></pattern>
      <pattern id="dots" width="7" height="7" patternUnits="userSpaceOnUse"><circle cx="1.5" cy="1.5" r="0.8" fill="#AFB89A" opacity="0.5"/></pattern>
      <radialGradient id="vig" cx="48%" cy="44%" r="75%"><stop offset="66%" stopColor="#000" stopOpacity="0"/><stop offset="100%" stopColor="#3a2f1d" stopOpacity="0.12"/></radialGradient>
      <linearGradient id="age" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#e8cfa3" stopOpacity="0.06"/><stop offset="0.5" stopColor="#000" stopOpacity="0"/><stop offset="1" stopColor="#8a6a3a" stopOpacity="0.08"/></linearGradient>
      </defs>
      <rect width="1200" height="720" fill="#ECE3D0"/>
      <rect width="1200" height="720" fill="#C3CFC9"/>
      <path d="M 0 0 L 1200 0 L 1200 316.0 L 1200.0 316.0 L 1148.6 320.0 L 1080.0 324.0 L 977.1 340.0 L 942.9 352.0 L 908.6 356.0 L 857.1 372.0 L 822.9 384.0 L 797.1 392.0 L 784.3 408.0 L 771.4 396.0 L 720.0 416.0 L 668.6 472.0 L 617.1 488.0 L 557.1 528.0 L 531.4 540.0 L 497.1 536.0 L 428.6 560.0 L 342.9 624.0 L 265.7 664.0 L 188.6 640.0 L 0.0 600.0 L 0 600.0 Z" fill="#D9CEB2" filter="url(#rough)"/>
      <g filter="url(#rough)">
      <path d="M 0.0 0.0 L 325.7 0.0 L 325.7 600.0 L 0.0 600.0 Z" fill="#D7CCAD" opacity="0.65"/>
      <path d="M 325.7 352.0 L 762.9 352.0 L 762.9 576.0 L 325.7 576.0 Z" fill="#D0C4A2" opacity="0.65"/>
      <path d="M 325.7 0.0 L 745.7 0.0 L 745.7 352.0 L 325.7 352.0 Z" fill="#DDD2B1" opacity="0.65"/>
      <path d="M 745.7 0.0 L 1200.0 0.0 L 1200.0 600.0 L 745.7 600.0 Z" fill="#D5CAA8" opacity="0.65"/>
      </g>
      <g filter="url(#rough)" fill="none" stroke="#796E57" strokeWidth="1" strokeDasharray="2 4" opacity="0.4">
      <path d="M 325.7 600.0 L 325.7 0.0"/>
      <path d="M 745.7 600.0 L 745.7 0.0"/>
      <path d="M 325.7 352.0 L 745.7 352.0"/>
      </g>
      <ellipse cx="745.7" cy="368.0" rx="42.9" ry="30.0" fill="url(#dots)" filter="url(#rough)"/>
      <ellipse cx="1002.9" cy="336.0" rx="38.6" ry="27.0" fill="url(#dots)" filter="url(#rough)"/>
      <ellipse cx="617.1" cy="208.0" rx="42.9" ry="30.0" fill="url(#dots)" filter="url(#rough)"/>
      <g stroke="#B7A98A" strokeWidth="1.4" opacity="0.5" filter="url(#rough)">
      <line x1="0" y1="224.0" x2="5" y2="217.0"/>
      <line x1="16" y1="229.7" x2="21" y2="222.7"/>
      <line x1="32" y1="232.0" x2="37" y2="225.0"/>
      <line x1="48" y1="229.4" x2="53" y2="222.4"/>
      <line x1="64" y1="223.5" x2="69" y2="216.5"/>
      <line x1="80" y1="217.9" x2="85" y2="210.9"/>
      <line x1="96" y1="216.0" x2="101" y2="209.0"/>
      <line x1="112" y1="218.9" x2="117" y2="211.9"/>
      <line x1="128" y1="224.9" x2="133" y2="217.9"/>
      <line x1="144" y1="230.3" x2="149" y2="223.3"/>
      <line x1="160" y1="231.9" x2="165" y2="224.9"/>
      <line x1="176" y1="228.7" x2="181" y2="221.7"/>
      <line x1="192" y1="222.6" x2="197" y2="215.6"/>
      <line x1="208" y1="217.4" x2="213" y2="210.4"/>
      <line x1="224" y1="216.2" x2="229" y2="209.2"/>
      <line x1="240" y1="219.7" x2="245" y2="212.7"/>
      <line x1="256" y1="225.9" x2="261" y2="218.9"/>
      <line x1="272" y1="230.9" x2="277" y2="223.9"/>
      <line x1="288" y1="231.7" x2="293" y2="224.7"/>
      <line x1="304" y1="227.9" x2="309" y2="220.9"/>
      <line x1="320" y1="221.7" x2="325" y2="214.7"/>
      <line x1="336" y1="216.9" x2="341" y2="209.9"/>
      <line x1="352" y1="216.4" x2="357" y2="209.4"/>
      <line x1="368" y1="220.5" x2="373" y2="213.5"/>
      <line x1="384" y1="226.7" x2="389" y2="219.7"/>
      <line x1="400" y1="231.3" x2="405" y2="224.3"/>
      <line x1="416" y1="231.4" x2="421" y2="224.4"/>
      <line x1="432" y1="227.1" x2="437" y2="220.1"/>
      <line x1="448" y1="220.8" x2="453" y2="213.8"/>
      <line x1="464" y1="216.5" x2="469" y2="209.5"/>
      <line x1="480" y1="216.8" x2="485" y2="209.8"/>
      <line x1="496" y1="221.4" x2="501" y2="214.4"/>
      <line x1="512" y1="227.6" x2="517" y2="220.6"/>
      <line x1="528" y1="231.6" x2="533" y2="224.6"/>
      <line x1="544" y1="231.0" x2="549" y2="224.0"/>
      <line x1="560" y1="226.2" x2="565" y2="219.2"/>
      <line x1="576" y1="220.0" x2="581" y2="213.0"/>
      <line x1="592" y1="216.2" x2="597" y2="209.2"/>
      <line x1="608" y1="217.2" x2="613" y2="210.2"/>
      <line x1="624" y1="222.3" x2="629" y2="215.3"/>
      <line x1="640" y1="228.4" x2="645" y2="221.4"/>
      <line x1="656" y1="231.9" x2="661" y2="224.9"/>
      <line x1="672" y1="230.5" x2="677" y2="223.5"/>
      <line x1="688" y1="225.3" x2="693" y2="218.3"/>
      <line x1="704" y1="219.2" x2="709" y2="212.2"/>
      <line x1="720" y1="216.1" x2="725" y2="209.1"/>
      <line x1="736" y1="217.7" x2="741" y2="210.7"/>
      <line x1="752" y1="223.2" x2="757" y2="216.2"/>
      <line x1="768" y1="229.2" x2="773" y2="222.2"/>
      <line x1="784" y1="232.0" x2="789" y2="225.0"/>
      <line x1="800" y1="230.0" x2="805" y2="223.0"/>
      <line x1="816" y1="224.3" x2="821" y2="217.3"/>
      <line x1="832" y1="218.5" x2="837" y2="211.5"/>
      <line x1="848" y1="216.0" x2="853" y2="209.0"/>
      <line x1="864" y1="218.4" x2="869" y2="211.4"/>
      <line x1="880" y1="224.1" x2="885" y2="217.1"/>
      <line x1="896" y1="229.8" x2="901" y2="222.8"/>
      <line x1="912" y1="232.0" x2="917" y2="225.0"/>
      <line x1="928" y1="229.3" x2="933" y2="222.3"/>
      <line x1="944" y1="223.4" x2="949" y2="216.4"/>
      <line x1="960" y1="217.9" x2="965" y2="210.9"/>
      <line x1="976" y1="216.0" x2="981" y2="209.0"/>
      <line x1="992" y1="219.1" x2="997" y2="212.1"/>
      <line x1="1008" y1="225.1" x2="1013" y2="218.1"/>
      <line x1="1024" y1="230.4" x2="1029" y2="223.4"/>
      <line x1="1040" y1="231.9" x2="1045" y2="224.9"/>
      <line x1="1056" y1="228.6" x2="1061" y2="221.6"/>
      <line x1="1072" y1="222.5" x2="1077" y2="215.5"/>
      <line x1="1088" y1="217.3" x2="1093" y2="210.3"/>
      <line x1="1104" y1="216.2" x2="1109" y2="209.2"/>
      <line x1="1120" y1="219.8" x2="1125" y2="212.8"/>
      <line x1="1136" y1="226.0" x2="1141" y2="219.0"/>
      <line x1="1152" y1="230.9" x2="1157" y2="223.9"/>
      <line x1="1168" y1="231.7" x2="1173" y2="224.7"/>
      <line x1="1184" y1="227.8" x2="1189" y2="220.8"/>
      </g>
      <path d="M 0.0 600.0 L 188.6 640.0 L 265.7 664.0 L 342.9 624.0 L 428.6 560.0 L 497.1 536.0 L 531.4 540.0 L 557.1 528.0 L 617.1 488.0 L 668.6 472.0 L 720.0 416.0 L 771.4 396.0 L 784.3 408.0 L 797.1 392.0 L 822.9 384.0 L 857.1 372.0 L 908.6 356.0 L 942.9 352.0 L 977.1 340.0 L 1080.0 324.0 L 1148.6 320.0 L 1200.0 316.0 L 1200.0 720.0 L 0.0 720.0 Z" fill="#C3CFC9"/>
      <path d="M 0.0 600.0 L 188.6 640.0 L 265.7 664.0 L 342.9 624.0 L 428.6 560.0 L 497.1 536.0 L 531.4 540.0 L 557.1 528.0 L 617.1 488.0 L 668.6 472.0 L 720.0 416.0 L 771.4 396.0 L 784.3 408.0 L 797.1 392.0 L 822.9 384.0 L 857.1 372.0 L 908.6 356.0 L 942.9 352.0 L 977.1 340.0 L 1080.0 324.0 L 1148.6 320.0 L 1200.0 316.0 L 1200.0 720.0 L 0.0 720.0 Z" fill="url(#stipple)"/>
      <path d="M 0.0 609.6 L 188.6 649.6 L 265.7 673.6 L 342.9 633.6 L 428.6 569.6 L 497.1 545.6 L 531.4 549.6 L 557.1 537.6 L 617.1 497.6 L 668.6 481.6 L 720.0 425.6 L 771.4 405.6 L 784.3 417.6 L 797.1 401.6 L 822.9 393.6 L 857.1 381.6 L 908.6 365.6 L 942.9 361.6 L 977.1 349.6 L 1080.0 333.6 L 1148.6 329.6 L 1200.0 325.6" fill="none" stroke="#AFC0B8" strokeWidth="0.8" opacity="0.45"/>
      <path d="M 0.0 622.4 L 188.6 662.4 L 265.7 686.4 L 342.9 646.4 L 428.6 582.4 L 497.1 558.4 L 531.4 562.4 L 557.1 550.4 L 617.1 510.4 L 668.6 494.4 L 720.0 438.4 L 771.4 418.4 L 784.3 430.4 L 797.1 414.4 L 822.9 406.4 L 857.1 394.4 L 908.6 378.4 L 942.9 374.4 L 977.1 362.4 L 1080.0 346.4 L 1148.6 342.4 L 1200.0 338.4" fill="none" stroke="#AFC0B8" strokeWidth="0.8" opacity="0.45"/>
      <path d="M 0.0 640.0 L 188.6 680.0 L 265.7 704.0 L 342.9 664.0 L 428.6 600.0 L 497.1 576.0 L 531.4 580.0 L 557.1 568.0 L 617.1 528.0 L 668.6 512.0 L 720.0 456.0 L 771.4 436.0 L 784.3 448.0 L 797.1 432.0 L 822.9 424.0 L 857.1 412.0 L 908.6 396.0 L 942.9 392.0 L 977.1 380.0 L 1080.0 364.0 L 1148.6 360.0 L 1200.0 356.0" fill="none" stroke="#AFC0B8" strokeWidth="0.8" opacity="0.45"/>
      <path d="M 0.0 600.0 L 188.6 640.0 L 265.7 664.0 L 342.9 624.0 L 428.6 560.0 L 497.1 536.0 L 531.4 540.0 L 557.1 528.0 L 617.1 488.0 L 668.6 472.0 L 720.0 416.0 L 771.4 396.0 L 784.3 408.0 L 797.1 392.0 L 822.9 384.0 L 857.1 372.0 L 908.6 356.0 L 942.9 352.0 L 977.1 340.0 L 1080.0 324.0 L 1148.6 320.0 L 1200.0 316.0" fill="none" stroke="#5C6B5C" strokeWidth="2.4" opacity="0.7" filter="url(#rough)"/>
      <path d="M 0.0 600.0 L 188.6 640.0 L 265.7 664.0 L 342.9 624.0 L 428.6 560.0 L 497.1 536.0 L 531.4 540.0 L 557.1 528.0 L 617.1 488.0 L 668.6 472.0 L 720.0 416.0 L 771.4 396.0 L 784.3 408.0 L 797.1 392.0 L 822.9 384.0 L 857.1 372.0 L 908.6 356.0 L 942.9 352.0 L 977.1 340.0 L 1080.0 324.0 L 1148.6 320.0 L 1200.0 316.0" fill="none" stroke="#5C6B5C" strokeWidth="0.8" opacity="0.4" strokeDasharray="1 3"/>
      <polygon points="522.9,540.0 548.6,552.0 574.3,548.0 552.9,537.6" fill="#D9CEB2" stroke="#5C6B5C" strokeWidth="1" opacity="0.9"/>
      <g stroke="#6E654F" strokeWidth="0.8" opacity="0.18">
      <line x1="214.3" y1="0" x2="214.3" y2="720"/>
      <line x1="428.6" y1="0" x2="428.6" y2="720"/>
      <line x1="642.9" y1="0" x2="642.9" y2="720"/>
      <line x1="857.1" y1="0" x2="857.1" y2="720"/>
      <line x1="1071.4" y1="0" x2="1071.4" y2="720"/>
      <line x1="0" y1="40.0" x2="1200" y2="40.0"/>
      <line x1="0" y1="240.0" x2="1200" y2="240.0"/>
      <line x1="0" y1="440.0" x2="1200" y2="440.0"/>
      <line x1="0" y1="640.0" x2="1200" y2="640.0"/>
      </g>
      <g fill="#6E654F" opacity="0.45" fontFamily="var(--font-mono, monospace)" fontSize="9" letterSpacing="0.5">
      <text x="431.6" y="14">79°30'W</text>
      <text x="860.1" y="14">79°00'W</text>
      <text x="1074.4" y="14">78°45'W</text>
      <text x="4" y="237.0">44°00'N</text>
      <text x="4" y="437.0">43°45'N</text>
      </g>
      <g fill="none" stroke="#A6B8B4" strokeWidth="2" opacity="0.7" filter="url(#rough)">
      <path d="M 308.6 296.0 L 377.1 392.0 L 428.6 464.0 L 454.3 532.0"/>
      <path d="M 531.4 408.0 L 548.6 472.0 L 557.1 524.0"/>
      <path d="M 677.1 320.0 L 720.0 392.0 L 754.3 456.0 L 767.1 508.0"/>
      <path d="M 102.9 464.0 L 180.0 560.0 L 257.1 608.0 L 308.6 640.0"/>
      <path d="M 771.4 288.0 L 788.6 352.0 L 797.1 396.0"/>
      <path d="M 985.7 256.0 L 1002.9 304.0 L 1011.4 320.0"/>
      </g>
      <g stroke="#5A5040" strokeWidth="1.1" opacity="0.5" strokeDasharray="6 3">
      <path d="M 42.9 528.0 L 428.6 504.0 L 857.1 376.0 L 1200.0 312.0" fill="none"/>
      </g>
      <path d="M 42.9 512.0 L 257.1 488.0 L 385.7 472.0 L 531.4 452.0 L 642.9 412.0 L 780.0 364.0 L 900.0 332.0 L 1011.4 316.0 L 1148.6 300.0 L 1200.0 296.0" fill="none" stroke="#6E4A35" strokeWidth="4.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.85" filter="url(#rough)"/>
      <path d="M 42.9 512.0 L 257.1 488.0 L 385.7 472.0 L 531.4 452.0 L 642.9 412.0 L 780.0 364.0 L 900.0 332.0 L 1011.4 316.0 L 1148.6 300.0 L 1200.0 296.0" fill="none" stroke="#9C6B4B" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
      <path d="M 128.6 448.0 L 291.4 388.0 L 471.4 344.0 L 668.6 308.0 L 840.0 280.0 L 942.9 268.0" fill="none" stroke="#6E4A35" strokeWidth="4.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.85" filter="url(#rough)"/>
      <path d="M 128.6 448.0 L 291.4 388.0 L 471.4 344.0 L 668.6 308.0 L 840.0 280.0 L 942.9 268.0" fill="none" stroke="#9C6B4B" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
      <path d="M 415.7 448.0 L 411.4 320.0 L 398.6 200.0 L 385.7 0.0" fill="none" stroke="#6E4A35" strokeWidth="4.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.85" filter="url(#rough)"/>
      <path d="M 415.7 448.0 L 411.4 320.0 L 398.6 200.0 L 385.7 0.0" fill="none" stroke="#9C6B4B" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
      <path d="M 552.9 480.0 L 544.3 360.0 L 514.3 240.0 L 488.6 0.0" fill="none" stroke="#6E4A35" strokeWidth="4.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.85" filter="url(#rough)"/>
      <path d="M 552.9 480.0 L 544.3 360.0 L 514.3 240.0 L 488.6 0.0" fill="none" stroke="#9C6B4B" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
      <path d="M 514.3 532.0 L 385.7 564.0 L 265.7 648.0 L 171.4 680.0" fill="none" stroke="#6E4A35" strokeWidth="4.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.85" filter="url(#rough)"/>
      <path d="M 514.3 532.0 L 385.7 564.0 L 265.7 648.0 L 171.4 680.0" fill="none" stroke="#9C6B4B" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
      <path d="M 904.3 336.0 L 900.0 264.0 L 895.7 192.0" fill="none" stroke="#6E4A35" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.85" filter="url(#rough)"/>
      <path d="M 904.3 336.0 L 900.0 264.0 L 895.7 192.0" fill="none" stroke="#9C6B4B" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/>
      <path d="M 754.3 252.0 L 805.7 160.0 L 882.9 64.0 L 925.7 0.0" fill="none" stroke="#6E4A35" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.85" filter="url(#rough)"/>
      <path d="M 754.3 252.0 L 805.7 160.0 L 882.9 64.0 L 925.7 0.0" fill="none" stroke="#9C6B4B" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/>
      <path d="M 42.9 408.0 L 257.1 400.0 L 428.6 376.0 L 625.7 352.0 L 805.7 328.0 L 1028.6 280.0" fill="none" stroke="#6E4A35" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.85" filter="url(#rough)"/>
      <path d="M 42.9 408.0 L 257.1 400.0 L 428.6 376.0 L 625.7 352.0 L 805.7 328.0 L 1028.6 280.0" fill="none" stroke="#9C6B4B" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/>
      <g><rect x="846.1" y="344.0" width="22" height="16" rx="3" fill="#ECE3D0" stroke="#6E4A35" strokeWidth="1.2"/><text x="857.1" y="356.0" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="10" fontWeight="700" fill="#6E4A35">401</text></g>
      <g><rect x="554.7" y="308.0" width="22" height="16" rx="3" fill="#ECE3D0" stroke="#6E4A35" strokeWidth="1.2"/><text x="565.7" y="320.0" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="10" fontWeight="700" fill="#6E4A35">407</text></g>
      <g><rect x="387.6" y="136.0" width="22" height="16" rx="3" fill="#ECE3D0" stroke="#6E4A35" strokeWidth="1.2"/><text x="398.6" y="148.0" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="10" fontWeight="700" fill="#6E4A35">400</text></g>
      <g><rect x="494.7" y="176.0" width="22" height="16" rx="3" fill="#ECE3D0" stroke="#6E4A35" strokeWidth="1.2"/><text x="505.7" y="188.0" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="10" fontWeight="700" fill="#6E4A35">404</text></g>
      <g><rect x="280.4" y="616.0" width="22" height="16" rx="3" fill="#ECE3D0" stroke="#6E4A35" strokeWidth="1.2"/><text x="291.4" y="628.0" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="10" fontWeight="700" fill="#6E4A35">QEW</text></g>
      <g><rect x="848.1" y="104.0" width="18" height="16" rx="3" fill="#ECE3D0" stroke="#6E4A35" strokeWidth="1.2"/><text x="857.1" y="116.0" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="10" fontWeight="700" fill="#6E4A35">12</text></g>
      <g><rect x="693.9" y="332.0" width="18" height="16" rx="3" fill="#ECE3D0" stroke="#6E4A35" strokeWidth="1.2"/><text x="702.9" y="344.0" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="10" fontWeight="700" fill="#6E4A35">7</text></g>
      <g>
      <circle cx="204.0" cy="455.2" r="3.0" fill="#4A4233" opacity="0.92"/>
      <text x="210.0" y="459.62" fontFamily="var(--font-display, Georgia, serif)" fontSize="13" fontWeight="600" fill="#4A4233" opacity="0.92">Brampton</text>
      <circle cx="568.3" cy="354.4" r="3.0" fill="#4A4233" opacity="0.92"/>
      <text x="574.3" y="358.82" fontFamily="var(--font-display, Georgia, serif)" fontSize="13" fontWeight="600" fill="#4A4233" opacity="0.92">Markham</text>
      <circle cx="421.7" cy="370.4" r="3.0" fill="#4A4233" opacity="0.92"/>
      <text x="427.7" y="374.82" fontFamily="var(--font-display, Georgia, serif)" fontSize="13" fontWeight="600" fill="#4A4233" opacity="0.92">Vaughan</text>
      <circle cx="657.4" cy="421.6" r="3.0" fill="#4A4233" opacity="0.92"/>
      <text x="663.4" y="426.02000000000004" fontFamily="var(--font-display, Georgia, serif)" fontSize="13" fontWeight="600" fill="#4A4233" opacity="0.92">Scarborough</text>
      <circle cx="462.0" cy="192.8" r="3.0" fill="#4A4233" opacity="0.92"/>
      <text x="468.0" y="197.22" fontFamily="var(--font-display, Georgia, serif)" fontSize="13" fontWeight="600" fill="#4A4233" opacity="0.92">Newmarket</text>
      <circle cx="1124.6" cy="310.4" r="3.0" fill="#4A4233" opacity="0.92"/>
      <text x="1118.6" y="314.82" textAnchor="end" fontFamily="var(--font-display, Georgia, serif)" fontSize="13" fontWeight="600" fill="#4A4233" opacity="0.92">Bowmanville</text>
      <circle cx="480.0" cy="334.4" r="2.2" fill="#4A4233" opacity="0.8"/>
      <text x="485.2" y="338.14" fontFamily="var(--font-display, Georgia, serif)" fontSize="11" fontWeight="500" fill="#4A4233" opacity="0.8">Richmond Hill</text>
      <circle cx="471.4" cy="235.2" r="2.2" fill="#4A4233" opacity="0.8"/>
      <text x="476.59999999999997" y="238.94" fontFamily="var(--font-display, Georgia, serif)" fontSize="11" fontWeight="500" fill="#4A4233" opacity="0.8">Aurora</text>
      <circle cx="503.1" cy="424.0" r="2.2" fill="#4A4233" opacity="0.8"/>
      <text x="508.3" y="427.74" fontFamily="var(--font-display, Georgia, serif)" fontSize="11" fontWeight="500" fill="#4A4233" opacity="0.8">North York</text>
      <circle cx="371.1" cy="516.8" r="2.2" fill="#4A4233" opacity="0.8"/>
      <text x="376.3" y="520.54" fontFamily="var(--font-display, Georgia, serif)" fontSize="11" fontWeight="500" fill="#4A4233" opacity="0.8">Etobicoke</text>
      <circle cx="268.3" cy="666.4" r="2.2" fill="#4A4233" opacity="0.8"/>
      <text x="273.5" y="670.14" fontFamily="var(--font-display, Georgia, serif)" fontSize="11" fontWeight="500" fill="#4A4233" opacity="0.8">Oakville</text>
      <circle cx="647.1" cy="263.2" r="2.2" fill="#4A4233" opacity="0.8"/>
      <text x="652.3000000000001" y="266.94" fontFamily="var(--font-display, Georgia, serif)" fontSize="11" fontWeight="500" fill="#4A4233" opacity="0.8">Stouffville</text>
      <circle cx="904.3" cy="154.4" r="2.2" fill="#4A4233" opacity="0.8"/>
      <text x="909.5" y="158.14000000000001" fontFamily="var(--font-display, Georgia, serif)" fontSize="11" fontWeight="500" fill="#4A4233" opacity="0.8">Port Perry</text>
      <circle cx="889.7" cy="268.0" r="2.2" fill="#4A4233" opacity="0.8"/>
      <text x="894.9000000000001" y="271.74" fontFamily="var(--font-display, Georgia, serif)" fontSize="11" fontWeight="500" fill="#4A4233" opacity="0.8">Brooklin</text>
      <circle cx="1047.4" cy="298.4" r="2.2" fill="#4A4233" opacity="0.8"/>
      <text x="1042.2" y="302.14" textAnchor="end" fontFamily="var(--font-display, Georgia, serif)" fontSize="11" fontWeight="500" fill="#4A4233" opacity="0.8">Courtice</text>
      <circle cx="229.7" cy="339.2" r="2.2" fill="#4A4233" opacity="0.8"/>
      <text x="234.89999999999998" y="342.94" fontFamily="var(--font-display, Georgia, serif)" fontSize="11" fontWeight="500" fill="#4A4233" opacity="0.8">Bolton</text>
      <circle cx="404.6" cy="299.2" r="2.2" fill="#4A4233" opacity="0.8"/>
      <text x="409.8" y="302.94" fontFamily="var(--font-display, Georgia, serif)" fontSize="11" fontWeight="500" fill="#4A4233" opacity="0.8">King City</text>
      <circle cx="315.4" cy="366.4" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="319.9" y="369.46" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Kleinburg</text>
      <circle cx="421.7" cy="357.6" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="426.2" y="360.66" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Maple</text>
      <circle cx="493.7" cy="391.2" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="498.2" y="394.26" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Thornhill</text>
      <circle cx="590.6" cy="352.0" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="595.1" y="355.06" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Unionville</text>
      <circle cx="616.3" cy="408.8" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="620.8" y="411.86" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Agincourt</text>
      <circle cx="741.4" cy="270.4" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="745.9" y="273.46" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Claremont</text>
      <circle cx="745.7" cy="231.2" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="750.2" y="234.26" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Goodwood</text>
      <circle cx="812.6" cy="144.8" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="817.1" y="147.86" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Greenbank</text>
      <circle cx="584.6" cy="132.0" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="589.1" y="135.06" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Mount Albert</text>
      <circle cx="488.6" cy="157.6" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="493.1" y="160.66" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Sharon</text>
      <circle cx="271.7" cy="237.6" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="276.2" y="240.66" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Schomberg</text>
      <circle cx="300.0" cy="311.2" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="304.5" y="314.26" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Nobleton</text>
      <circle cx="721.7" cy="321.6" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="726.2" y="324.66" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Whitevale</text>
      <circle cx="768.9" cy="295.2" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="773.4" y="298.26" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Brougham</text>
      <circle cx="872.6" cy="239.2" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="877.1" y="242.26" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Ashburn</text>
      <circle cx="915.4" cy="239.2" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="919.9" y="242.26" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Myrtle</text>
      <circle cx="1061.1" cy="262.4" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="1056.6" y="265.46" textAnchor="end" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Hampton</text>
      <circle cx="1178.6" cy="254.4" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="1174.1" y="257.46" textAnchor="end" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Orono</text>
      <circle cx="856.3" cy="305.6" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="860.8" y="308.66" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Kinsale</text>
      <circle cx="942.0" cy="254.4" r="1.5" fill="#4A4233" opacity="0.62"/>
      <text x="946.5" y="257.46" fontFamily="var(--font-display, Georgia, serif)" fontSize="9" fontWeight="400" fill="#4A4233" opacity="0.62">Columbus</text>
      </g>
      <g fontFamily="var(--font-mono, monospace)" fill="#796E57" opacity="0.5" fontSize="13" letterSpacing="3" textAnchor="middle">
      <text x="154.3" y="96.0">PEEL</text>
      <text x="514.3" y="48.0">YORK  REGION</text>
      <text x="514.3" y="512.0">CITY OF TORONTO</text>
      <text x="1045.7" y="112.0">DURHAM  REGION</text>
      </g>
      <text x="900.0" y="664.0" fontFamily="var(--font-display, Georgia, serif)" fontStyle="italic" fontSize="34" letterSpacing="10" fill="#5C6B5C" opacity="0.6" textAnchor="middle">Lake Ontario</text>
      <g transform="translate(92 116)" opacity="0.72">
      <circle r="34" fill="none" stroke="#4A4233" strokeWidth="1" opacity="0.5"/>
      <circle r="27" fill="none" stroke="#4A4233" strokeWidth="0.6" opacity="0.35"/>
      <line x1="0" y1="0" x2="0.0" y2="-30.0" stroke="#796E57" strokeWidth="1.2"/>
      <line x1="0" y1="0" x2="14.1" y2="-14.1" stroke="#796E57" strokeWidth="0.7"/>
      <line x1="0" y1="0" x2="30.0" y2="-0.0" stroke="#796E57" strokeWidth="1.2"/>
      <line x1="0" y1="0" x2="14.1" y2="14.1" stroke="#796E57" strokeWidth="0.7"/>
      <line x1="0" y1="0" x2="0.0" y2="30.0" stroke="#796E57" strokeWidth="1.2"/>
      <line x1="0" y1="0" x2="-14.1" y2="14.1" stroke="#796E57" strokeWidth="0.7"/>
      <line x1="0" y1="0" x2="-30.0" y2="0.0" stroke="#796E57" strokeWidth="1.2"/>
      <line x1="0" y1="0" x2="-14.1" y2="-14.1" stroke="#796E57" strokeWidth="0.7"/>
      <path d="M0 -32 L6 0 L0 5 L-6 0 Z" fill="#9C6B4B"/>
      <path d="M0 32 L6 0 L0 -5 L-6 0 Z" fill="#4A4233" opacity="0.55"/>
      <circle r="2.5" fill="#4A4233"/>
      <text x="0" y="-38" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="12" fontWeight="700" fill="#4A4233">N</text>
      </g>
      <g>
      <rect x="40.0" y="676" width="36.0" height="7" fill="#4A4233" stroke="#4A4233" strokeWidth="0.8"/>
      <rect x="76.0" y="676" width="36.0" height="7" fill="#ECE3D0" stroke="#4A4233" strokeWidth="0.8"/>
      <rect x="112.0" y="676" width="36.0" height="7" fill="#4A4233" stroke="#4A4233" strokeWidth="0.8"/>
      <rect x="148.0" y="676" width="36.0" height="7" fill="#ECE3D0" stroke="#4A4233" strokeWidth="0.8"/>
      <text x="40.0" y="671" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="9" fill="#4A4233">0</text>
      <text x="76.0" y="671" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="9" fill="#4A4233">5</text>
      <text x="112.0" y="671" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="9" fill="#4A4233">10</text>
      <text x="148.0" y="671" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="9" fill="#4A4233">15</text>
      <text x="184.0" y="671" textAnchor="middle" fontFamily="var(--font-mono, monospace)" fontSize="9" fill="#4A4233">20 km</text>
      </g>
      <rect width="1200" height="720" fill="url(#age)"/>
      <rect width="1200" height="720" fill="url(#vig)"/>
      <rect width="1200" height="720" fill="#4A4233" filter="url(#grain)" opacity="0.35"/>
      <rect x="10" y="10" width="1180" height="700" fill="none" stroke="#6E4A35" strokeWidth="2" opacity="0.6"/>
      <rect x="16" y="16" width="1168" height="688" fill="none" stroke="#6E4A35" strokeWidth="0.8" opacity="0.45"/>
      <circle cx="16" cy="16" r="3.5" fill="#6E4A35" opacity="0.6"/>
      <circle cx="1184" cy="16" r="3.5" fill="#6E4A35" opacity="0.6"/>
      <circle cx="16" cy="704" r="3.5" fill="#6E4A35" opacity="0.6"/>
      <circle cx="1184" cy="704" r="3.5" fill="#6E4A35" opacity="0.6"/>
      </svg>
  );
}